#!/usr/bin/perl
#
# gasmailer
#
# Simple script for sending personalised emails
#

use strict;
use warnings;

my $response    = zenity_menu();

if ($response eq 'welcome') {
    welcome();
}

exit;

sub welcome {
    my $email_address = zenity_text("Enter email address");

    use File::Slurp;
    my $text = read_file('welcome/email.markdown');

    use Text::Markdown::Hoedown;
    my $html = markdown($text);

    use Email::Stuffer;
    Email::Stuffer  ->to($email_address)
                    ->from('chrisjrob@gmail.com')
                    ->subject('Welcome to Guildford Art Society')
                    ->html_body($html)
                    ->attach_file('welcome/attachments/test.pdf')
                    ->send;

}

sub zenity_text {
    my $prompt = shift;

    my $response = `zenity --title "GAS Mailer" --entry --text "$prompt"`; 
    chomp($response);

    return $response;
}

sub zenity_menu {

    my $response = `zenity  --list --title "GAS Mailer" --text "Select an option" --radiolist  --column "Pick" --column "Option" TRUE "Send email to new member"`;

    chomp($response);

    if ($response eq 'Send email to new member') {
        return 'welcome';
    } else {
        print "Unexpect: $response\n";
    }


}
